plugins {
    id 'com.android.application'
}

android {
    namespace 'de.roman.mercedesobdmonitor'
    compileSdk 37

    defaultConfig {
        applicationId 'de.roman.mercedesobdmonitor'
        minSdk 26
        targetSdk 37
        versionCode 1
        versionName '1.0.0'
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
